development:
  host: localhost
  database: fire_development

test:
  host: localhost
  database: fire_test

# set these environment variables on your prod server
production:
  host: localhost
  username: <%= ENV['MONGOID_USERNAME'] %>
  password: <%= ENV['MONGOID_PASSWORD'] %>
  database: fire_production
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
