defaults: &defaults
  linked_in_api_key: ck3wuu87qgvc
  linked_in_api_secret: L2F4WZADMAdieNXr

development:
  <<: *defaults

test:
  linked_in_api_key: g4jdbhrdzh1j
  linked_in_api_secret: aKqlexiFDyxmihVj

production:
  <<: *defaults